// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func NewWireTest() (*ReturnType, error) {
	v := ProvideOptions()
	options := ProvideOption(v...)
	v2 := ProvideOptionsTwo()
	optionsTwo := ProvideOptionTwo(v2...)
	returnType, err := ProvideCollector(options, optionsTwo)
	if err != nil {
		return nil, err
	}
	return returnType, nil
}
